In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
N = 10

In [4]:
D = 3

In [18]:
X = np.zeros((N,D))
X[:,0] = 1 #BIAS TERM
X[:5,1]=1

In [19]:
print(X)

[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [23]:
Y = np.array([0]*5 +[1]*5)

In [29]:
#gradient descent 
costs =[]
w = np.random.randn(D) / np.sqrt(D)
learning_rate = 0.001

In [30]:
for t in range(1000):
    Yhat = X.dot(w)
    delta = Yhat - Y
    w = w - learning_rate * X.T.dot(delta) #T is X transpose
    mse = delta.dot(delta)/ N
    costs.append (mse)

In [31]:
plt.plot(costs)

In [32]:
w

array([ 0.86292396, -0.77820949, -0.33665437])